export const colors = [
  '#5F87FF',
  '#FFDD63',
  '#62CE6C',
  '#FFA455',
  '#60BCFA',
  '#DB7892',
  '#5D9BA4',
  '#FFB7AE',
  '#04A375',
  '#D770E0',
  '#7569AB',
  '#FF7955',
];

// 图表Chart的默认高度
export const DEAULT_CHART_HEIGHT = 300;
export const DEFAULT_OTERH_COLOR = '#CACEDB';
export const DISABLE_COLOR = '#ADB2C2';
export const DEFAULT_LINEDASH = [2, 5];
export const DEFAULT_MIN_HEIGHT = 4;
export const DEFAULT_REDIUS = [4, 4, 0, 0];
export const DEFAULT_REDIUS_BAR = [0, 2, 2, 0];

export const DEFAULT_FONT_COLOR = '#313E75';

export const BAR_TEXTURE =
  'data: image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA4AAAAOCAYAAAAfSC3RAAAABGdBTUEAALGPC/xhBQAA' +
  'ACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAhGVYSWZNTQAqAAAACAAFARIAAwAAAAEA' +
  'AQAAARoABQAAAAEAAABKARsABQAAAAEAAABSASgAAwAAAAEAAgAAh2kABAAAAAEAAABaAAAAAAAAAEgAAAABAAAASAAA' +
  'AAEAA6ABAAMAAAABAAEAAKACAAQAAAABAAAADqADAAQAAAABAAAADgAAAABOylT5AAAACXBIWXMAAAsTAAALEwEAmpwY' +
  'AAABWWlUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTpuczptZXRhLyIgeDp4' +
  'bXB0az0iWE1QIENvcmUgNi4wLjAiPgogICA8cmRmOlJERiB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkvM' +
  'DIvMjItcmRmLXN5bnRheC1ucyMiPgogICAgICA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIgogICAgICAgICAgIC' +
  'B4bWxuczp0aWZmPSJodHRwOi8vbnMuYWRvYmUuY29tL3RpZmYvMS4wLyI+CiAgICAgICAgIDx0aWZmOk9yaWVudGF0aW9' +
  'uPjE8L3RpZmY6T3JpZW50YXRpb24+CiAgICAgIDwvcmRmOkRlc2NyaXB0aW9uPgogICA8L3JkZjpSREY+CjwveDp4bXBt' +
  'ZXRhPgoZXuEHAAAAtElEQVQoFZWSCwqEMAxEBfc2tfe/h3obxW5e7EhaugsGytDPy2foVO44q26mebIwnTtNdrbWdycPB' +
  'EmBlw5SksXuuC+AhKDj3pbdVPCnJpECr4A8IgRJyZw6SHACzLbewN42CYEp38Nqf1R5BoqDCwa6bI3gpmKE3bUK9bAMay' +
  'o+gxsUYds+xtGRw5pRFUewXJaSNDPjL8tHhgneAflGb2A3DJCIsNqWxspyufmr/+D4SRz+AupSLeugHyqeAAAAAElFTkSuQmCC';

// Funnel Chart转换模式的临界值，是否显示转化率label
export const FUNNEL_CRITICAL_COUNT = 6;
